### ISSUE TITLE
Which fairseq files are used?

### ISSUE THREAD

**Issue by SirRob1997** [ShannonAI/fast-knn-nmt#4]
In the repo we have fairseq files in fast-knn-nmt/fast_knn_nmt/custom_fairseq/ as well as fast-knn-nmt/thirdparty/fairseq/ the files/changes to, for example, the `sequence_scorer.py` differ in these two. Which one is the correct one to use and why do the other ones exist?

**Comment by YuxianMeng** [comment]
@SirRob1997 Sorry for the confusion. The files in `third_party` is mainly used to extract features, and the files in `custom_fairseq` are codes that used for other purposes like computing ppl or bleu. Both of them are modified a little bit to serve their own purpose.

**Comment by SirRob1997** [comment]
Got it, might be worth mentioning that somewhere in the Readme. Thanks!
